import Head from 'next/head';
import { Fragment, useEffect, useRef, useState } from 'react';
import axios from 'axios';
import md5 from 'md5'
import Header from '../../../components/Header';
import { ThemeProvider } from 'styled-components';
import { ResetCSS } from '../../global/styles/resetCSS';
import { THEME } from '../../global/styles/theme';
import SectionCharacters from '../../../components/SectionCharacters';

export default function Home() {

  const ref = useRef(null)

  const closeSidebar = (event: any) => {
    //@ts-ignore
    if (ref.current && !ref.current.contains(event.target)) {
      setSidebar(false)
    }
  }

  useEffect(() => {
    document.addEventListener('click', closeSidebar, true)
      return () => {
      document.removeEventListener('click', closeSidebar, true)
      }
  }, [])

  const [sidebar, setSidebar] = useState(false)

  return (
    <Fragment>
      <Head>
        <title>Marvel Universe - Characters</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Kanit:wght@300&display=swap" rel="stylesheet" />
      </Head>
      <ThemeProvider theme={THEME}>
        <ResetCSS />
        <div ref={ref} onClick={closeSidebar} />
        <Header sidebar={sidebar} setSidebar={setSidebar}/>
        <SectionCharacters />
      </ThemeProvider>
    </Fragment>
  )
}
