import Head from 'next/head';
import { ThemeProvider } from 'styled-components';
import { ResetCSS } from '../global/styles/resetCSS';
import { THEME } from '../global/styles/theme';

export default function Home() {
  return (
    <>
      <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
      <ThemeProvider theme={THEME}>
        <ResetCSS />
        <h1>Hello World</h1>
      </ThemeProvider>
    </>
  )
}
